#!/bin/bash -

# anything's possible

# some variables
SITENAME=director.local
SITEDIR=/srv/http/$SITENAME
DB=director_db
DBPREFIX=ddb_
HTTPDROOT=/etc/httpd/conf/extra
REPO=/srv/http/repo.mystframework.local/repo

# use regular script rules to set up and tear down things

if [ 1 -eq 1 ]
then
	rm -rf /srv/http/shalamar.local
	mysql -u root -e "drop database $DB" 2>/dev/null
	echo 'priming sudo command'
	sudo printf '' > /dev/null
	[ -L $HTTPDROOT/vhosts-enabled/$SITENAME ] && sudo rm $HTTPDROOT/vhosts-enabled/$SITENAME
	[ -f $HTTPDROOT/vhosts-available/$SITENAME ] && sudo rm $HTTPDROOT/vhosts-available/$SITENAME
fi


if [ 1 -eq 1 ]
then

	echo "myst --create --name shalamar.local -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource $DB"
	myst --create --name shalamar.local -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource $DB
	read

# Why does a name need to specified?
	echo 'myst --folder /srv/http/shalamar.local --finalize'
	myst --folder /srv/http/shalamar.local --finalize
	read

# Activate this for use with Apache
	echo "sudo cp /srv/http/$SITENAME/misc/apache.vhost $HTTPDROOT/vhosts-available/$SITENAME"
	sudo cp /srv/http/$SITENAME/misc/apache.vhost $HTTPDROOT/vhosts-available/$SITENAME
	echo "sudo ln -s $HTTPDROOT/vhosts-available/$SITENAME $HTTPDROOT/vhosts-enabled/"
	sudo ln -s $HTTPDROOT/vhosts-available/$SITENAME $HTTPDROOT/vhosts-enabled/

# Create a datasource
	echo "mystdb --create --generate -f $SITEDIR --mysql --verbose --name $DB --user root"
	mystdb --create --generate -f $SITEDIR --mysql --verbose --name $DB --user root

# echo 'examine the generated datasource'
#	less $SITEDIR/Application.cfc 
	read

# Finally, restart the server
	echo "sudo systemctl restart httpd && sudo systemctl restart lucee"
	sudo systemctl restart httpd && sudo systemctl restart lucee
	echo "Done..."
	read

# Add a module (cms)... 
	echo "mystmod --install $REPO/cms --to $SITEDIR"
	mystmod --install $REPO/cms --to $SITEDIR
	read

# ...and set it up
	echo "mystmod --setup --address http://$SITENAME --module cms"
	mystmod --setup --address http://$SITENAME --module cms
	read

fi

# Check that everything took
if [ 1 -eq 1 ]
then
# Is the instance there?
	[ -d $SITEDIR ] || echo "TEST FAILED: Failed to create instance..." 
# Is the datasource specified in the instance?
	[ ! -z "`grep $DB $SITEDIR/Application.cfc 2>/dev/null`" ] || echo "TEST FAILED: Failed to add datasource..." 
# Can I get a packet from the server?
	wget -O- http://$SITENAME
# Did MySQL load tables?
	mysql -u root -e "use $DB; show tables;"
fi
